@server = http://localhost:3001

### UTENTI --------------------------------------------------------------------------------------------

### Login corretto - DOCENTE
POST {{server}}/api/sessions
Content-Type: application/json

{"email": "luigi.derussis@polito.it", 
"password": "prova123"}

### Login corretto - STUDENTE
POST {{server}}/api/sessions
Content-Type: application/json

{"email": "alice.rossi@studenti.polito.it", 
"password": "prova123"}

### Email/password errati per il login
POST {{server}}/api/sessions
Content-Type: application/json

{"email": "luigi.derussis@polito.it", 
"password": "gsgsgsgr"}

### Logout
DELETE {{server}}/api/sessions/current

### Controllo se l'utente è loggato
GET {{server}}/api/sessions/current

###DOCENTE --------------------------------------------------------------------------------------------

### Ottenere la lista degli studenti
GET {{server}}/api/docente/classe

### Ottenere le collaborazioni con `minCount` predefinito (2)
GET {{server}}/api/docente/classe/collaborazioni

### Creare un nuovo compito
POST {{server}}/api/docente/compiti
Content-Type: application/json

{
  "traccia": "Compito di prova",
  "studentiIds": [1, 2]
}

### Creare un nuovo compito - ERRORE troppi studenti selezionati
POST {{server}}/api/docente/compiti
Content-Type: application/json

{
  "traccia": "Compito di prova",
  "i": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
}

### Creare un nuovo compito - ERRORE supero limite collaborazioni tra studenti
POST {{server}}/api/docente/compiti
Content-Type: application/json

{
  "traccia": "Compito di prova",
  "i": [3, 4, 5]
}

### Ottenere la risposta di un compito
GET {{server}}/api/docente/compiti/2/rispondi

### Ottenere la risposta di un compito - ERRORE compito non esistente
GET {{server}}/api/docente/compiti/1000/rispondi

### Ottenere la risposta di un compito - ERRORE risposta non ancora esistente
GET {{server}}/api/docente/compiti/1/rispondi

### Aggiungere una valutazione a un compito - ERRORE risposta non ancora esistente
### SE ANCORA NON SI E' AGGIUNTA UNA RISPOSTA ALLA DOMANDA 1 PROVANDO LE API STUDENTI
PUT {{server}}/api/docente/compiti/1/valuta
Content-Type: application/json

{
  "punteggio": 29
}
### Aggiungere una valutazione a un compito
### ESEGUIRLA DOPO AVER AGGIUNTO UNA RISPOSTA ALLA DOMANDA 1 PROVANDO LE API STUDENTI
PUT {{server}}/api/docente/compiti/1/valuta
Content-Type: application/json

{
  "punteggio": 29
}

### Aggiungere una valutazione a un compito - ERRORE punteggio non valido
PUT {{server}}/api/docente/compiti/1/valuta
Content-Type: application/json

{
  "punteggio": 32
}

### Aggiungere una valutazione a un compito - ERRORE compito non esistente
PUT {{server}}/api/docente/compiti/11/valuta
Content-Type: application/json

{
  "punteggio": 29
}

### Aggiungere una valutazione a un compito - ERRORE compito già valutato
PUT {{server}}/api/docente/compiti/2/valuta
Content-Type: application/json

{
  "punteggio": 29
}

### Ottenere le statistiche della classe, ordinata per la media dei punteggi
GET {{server}}/api/docente/classe/stato?sort=media

### Ottenere le statistiche della classe, ordinata per alfabetico
GET {{server}}/api/docente/classe/stato?sort=alfabetico

### Ottenere le statistiche della classe, ordinata per il numero totale dei compiti assegnati
GET {{server}}/api/docente/classe/stato?sort=totale_compiti

### Ottenere le statistiche della classe - ERRORE parametro di ordinamento non valido
GET {{server}}/api/docente/classe/stato?sort=errore

### Ottenere tutti i compiti del docente
GET {{server}}/api/docente/compiti

### Ottenere tutti i compiti APERTI
GET {{server}}/api/docente/compiti?stato=aperto

### Ottenere tutti i compiti CHIUSI
GET {{server}}/api/docente/compiti?stato=chiuso

### Ottenere i compiti con filtro - ERRORE stato non valido
GET {{server}}/api/docente/compiti?stato=invalid

### Ottenere il dettaglio del compito con ID valido (es: 2)
GET {{server}}/api/docente/compiti/2

### Ottenere il dettaglio di un compito - ERRORE compito non esistente
GET {{server}}/api/docente/compiti/11

### Ottenere il dettaglio di un compito di un ALTRO docente - ERRORE
GET {{server}}/api/docente/compiti/3

###STUDENTE -------------------------------------------------------------------------------------------

### GET: Visualizza tutti i compiti dello studente (senza filtro)
GET {{server}}/api/studente/compiti

### GET: Visualizza tutti i compiti dello studente filtrati per stato "aperto"
GET {{server}}/api/studente/compiti?stato=aperto

### GET: Visualizza tutti i compiti dello studente filtrati per stato "chiuso"  
GET {{server}}/api/studente/compiti?stato=chiuso

###

### GET: Test con stato non valido - ERRORE stato non valido
GET {{server}}/api/studente/compiti?stato=invalido

### PUT: Inserisce risposta a un compito aperto (ID compito = 1)
PUT {{server}}/api/studente/compiti/1/rispondi
Content-Type: application/json

{
  "testo_risposta": "Questa è la mia risposta al primo compito. Ho analizzato il problema e propongo questa soluzione dettagliata."
}

### PUT: Aggiorna risposta esistente (ID compito = 1)
PUT {{server}}/api/studente/compiti/1/rispondi
Content-Type: application/json

{
  "testo_risposta": "Questa è la mia risposta aggiornata al primo compito. Ho rivisto la soluzione e apportato miglioramenti."
}

### PUT: Tentativo di risposta a compito - ERRORE compito non esistente
PUT {{server}}/api/studente/compiti/11/rispondi
Content-Type: application/json

{
  "testo_risposta": "Risposta test"
}

### PUT: Tentativo di risposta a compito - ERRORE non autorizzato
//DA ESEGUIRE DOPO CHE DOCENTE HA AGGIUNTO UN TERZO COMPITO PER ALTRI STUDENTI
PUT {{server}}/api/studente/compiti/3/rispondi
Content-Type: application/json

{
  "testo_risposta": "Risposta test"
}

### PUT: Tentativo di risposta a compito - ERRORE testo risposta vuoto
PUT {{server}}/api/studente/compiti/1/rispondi
Content-Type: application/json

{
  "testo_risposta": ""
}

### PUT: Tentativo di risposta a compito - ERRORE compito già chiuso
PUT {{server}}/api/studente/compiti/2/rispondi
Content-Type: application/json

{
  "testo_risposta": "Risposta al secondo compito assegnato."
}

### GET: Visualizza la media ponderata dello studente
GET {{server}}/api/studente/media

### GET: Visualizza dettagli compito specifico (ID = 1)
GET {{server}}/api/studente/compiti/1

### GET: Tentativo di visualizzare compito - ERRORE non autorizzato (da valutare controllo compito inesistente)
GET {{server}}/api/studente/compiti/3

